version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Prague
    groups:
      go-dependencies:
        patterns:
          - "*"
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Prague
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - dependencies
