// Code generated by betaflight-cli internal/generate. DO NOT EDIT.
// Source metadata derived from Betaflight 2026.6.1 under GPL-3.0-or-later.
// See LICENSE and THIRD_PARTY_NOTICES.md.
package msp

const GeneratedMSPSourceVersion = "2026.6.1"

const (
	MSPAPIVersion                uint16 = 0x1
	MSPFCVariant                 uint16 = 0x2
	MSPFCVersion                 uint16 = 0x3
	MSPBoardInfo                 uint16 = 0x4
	MSPBuildInfo                 uint16 = 0x5
	MSPName                      uint16 = 0xa
	MSPSetName                   uint16 = 0xb
	MSPBatteryConfig             uint16 = 0x20
	MSPSetBatteryConfig          uint16 = 0x21
	MSPModeRanges                uint16 = 0x22
	MSPSetModeRange              uint16 = 0x23
	MSPFeatureConfig             uint16 = 0x24
	MSPSetFeatureConfig          uint16 = 0x25
	MSPBoardAlignmentConfig      uint16 = 0x26
	MSPSetBoardAlignmentConfig   uint16 = 0x27
	MSPCurrentMeterConfig        uint16 = 0x28
	MSPSetCurrentMeterConfig     uint16 = 0x29
	MSPMixerConfig               uint16 = 0x2a
	MSPSetMixerConfig            uint16 = 0x2b
	MSPRXConfig                  uint16 = 0x2c
	MSPSetRXConfig               uint16 = 0x2d
	MSPLedColors                 uint16 = 0x2e
	MSPSetLedColors              uint16 = 0x2f
	MSPLedStripConfig            uint16 = 0x30
	MSPSetLedStripConfig         uint16 = 0x31
	MSPRSSIConfig                uint16 = 0x32
	MSPSetRSSIConfig             uint16 = 0x33
	MSPAdjustmentRanges          uint16 = 0x34
	MSPSetAdjustmentRange        uint16 = 0x35
	MSPCFSerialConfig            uint16 = 0x36
	MSPSetCFSerialConfig         uint16 = 0x37
	MSPVoltageMeterConfig        uint16 = 0x38
	MSPSetVoltageMeterConfig     uint16 = 0x39
	MSPSonarAltitude             uint16 = 0x3a
	MSPPIDController             uint16 = 0x3b
	MSPSetPIDController          uint16 = 0x3c
	MSPArmingConfig              uint16 = 0x3d
	MSPSetArmingConfig           uint16 = 0x3e
	MSPRXMap                     uint16 = 0x40
	MSPSetRXMap                  uint16 = 0x41
	MSPReboot                    uint16 = 0x44
	MSPDataflashSummary          uint16 = 0x46
	MSPDataflashRead             uint16 = 0x47
	MSPDataflashErase            uint16 = 0x48
	MSPFailsafeConfig            uint16 = 0x4b
	MSPSetFailsafeConfig         uint16 = 0x4c
	MSPRxfailConfig              uint16 = 0x4d
	MSPSetRxfailConfig           uint16 = 0x4e
	MSPSdcardSummary             uint16 = 0x4f
	MSPBlackboxConfig            uint16 = 0x50
	MSPSetBlackboxConfig         uint16 = 0x51
	MSPTransponderConfig         uint16 = 0x52
	MSPSetTransponderConfig      uint16 = 0x53
	MSPOSDConfig                 uint16 = 0x54
	MSPSetOSDConfig              uint16 = 0x55
	MSPOSDCharRead               uint16 = 0x56
	MSPOSDCharWrite              uint16 = 0x57
	MSPVTXConfig                 uint16 = 0x58
	MSPSetVTXConfig              uint16 = 0x59
	MSPAdvancedConfig            uint16 = 0x5a
	MSPSetAdvancedConfig         uint16 = 0x5b
	MSPFilterConfig              uint16 = 0x5c
	MSPSetFilterConfig           uint16 = 0x5d
	MSPPIDAdvanced               uint16 = 0x5e
	MSPSetPIDAdvanced            uint16 = 0x5f
	MSPSensorConfig              uint16 = 0x60
	MSPSetSensorConfig           uint16 = 0x61
	MSPCameraControl             uint16 = 0x62
	MSPSetArmingDisabled         uint16 = 0x63
	MSPStatus                    uint16 = 0x65
	MSPRawImu                    uint16 = 0x66
	MSPServo                     uint16 = 0x67
	MSPMotor                     uint16 = 0x68
	MSPRC                        uint16 = 0x69
	MSPRawGPS                    uint16 = 0x6a
	MSPCompGPS                   uint16 = 0x6b
	MSPAttitude                  uint16 = 0x6c
	MSPAltitude                  uint16 = 0x6d
	MSPAnalog                    uint16 = 0x6e
	MSPRCTuning                  uint16 = 0x6f
	MSPPID                       uint16 = 0x70
	MSPBoxnames                  uint16 = 0x74
	MSPPidnames                  uint16 = 0x75
	MSPWp                        uint16 = 0x76
	MSPBoxids                    uint16 = 0x77
	MSPServoConfigurations       uint16 = 0x78
	MSPNavStatus                 uint16 = 0x79
	MSPNavConfig                 uint16 = 0x7a
	MSPMotor3dConfig             uint16 = 0x7c
	MSPRCDeadband                uint16 = 0x7d
	MSPSensorAlignment           uint16 = 0x7e
	MSPLedStripModecolor         uint16 = 0x7f
	MSPVoltageMeters             uint16 = 0x80
	MSPCurrentMeters             uint16 = 0x81
	MSPBatteryState              uint16 = 0x82
	MSPMotorConfig               uint16 = 0x83
	MSPGPSConfig                 uint16 = 0x84
	MSPCompassConfig             uint16 = 0x85
	MSPESCSensorData             uint16 = 0x86
	MSPGPSRescue                 uint16 = 0x87
	MSPGPSRescuePids             uint16 = 0x88
	MSPVtxtableBand              uint16 = 0x89
	MSPVtxtablePowerlevel        uint16 = 0x8a
	MSPMotorTelemetry            uint16 = 0x8b
	MSPSimplifiedTuning          uint16 = 0x8c
	MSPSetSimplifiedTuning       uint16 = 0x8d
	MSPCalculateSimplifiedPID    uint16 = 0x8e
	MSPCalculateSimplifiedGyro   uint16 = 0x8f
	MSPCalculateSimplifiedDterm  uint16 = 0x90
	MSPValidateSimplifiedTuning  uint16 = 0x91
	MSPStatusEx                  uint16 = 0x96
	MSPUID                       uint16 = 0xa0
	MSPGpssvinfo                 uint16 = 0xa4
	MSPGpsstatistics             uint16 = 0xa6
	MSPAttitudeQuaternion        uint16 = 0xa7
	MSPOSDVideoConfig            uint16 = 0xb4
	MSPSetOSDVideoConfig         uint16 = 0xb5
	MSPDisplayport               uint16 = 0xb6
	MSPCopyProfile               uint16 = 0xb7
	MSPBeeperConfig              uint16 = 0xb8
	MSPSetBeeperConfig           uint16 = 0xb9
	MSPSetTxInfo                 uint16 = 0xba
	MSPTxInfo                    uint16 = 0xbb
	MSPSetOSDCanvas              uint16 = 0xbc
	MSPOSDCanvas                 uint16 = 0xbd
	MSPSetRawRC                  uint16 = 0xc8
	MSPSetRawGPS                 uint16 = 0xc9
	MSPSetPID                    uint16 = 0xca
	MSPSetRCTuning               uint16 = 0xcc
	MSPAccCalibration            uint16 = 0xcd
	MSPMagCalibration            uint16 = 0xce
	MSPResetConf                 uint16 = 0xd0
	MSPSetWp                     uint16 = 0xd1
	MSPSelectSetting             uint16 = 0xd2
	MSPSetHeading                uint16 = 0xd3
	MSPSetServoConfiguration     uint16 = 0xd4
	MSPSetMotor                  uint16 = 0xd6
	MSPSetNavConfig              uint16 = 0xd7
	MSPSetMotor3dConfig          uint16 = 0xd9
	MSPSetRCDeadband             uint16 = 0xda
	MSPSetResetCurrPID           uint16 = 0xdb
	MSPSetSensorAlignment        uint16 = 0xdc
	MSPSetLedStripModecolor      uint16 = 0xdd
	MSPSetMotorConfig            uint16 = 0xde
	MSPSetGPSConfig              uint16 = 0xdf
	MSPSetCompassConfig          uint16 = 0xe0
	MSPSetGPSRescue              uint16 = 0xe1
	MSPSetGPSRescuePids          uint16 = 0xe2
	MSPSetVtxtableBand           uint16 = 0xe3
	MSPSetVtxtablePowerlevel     uint16 = 0xe4
	MSPMultipleMsp               uint16 = 0xe6
	MSPModeRangesExtra           uint16 = 0xee
	MSPSetAccTrim                uint16 = 0xef
	MSPAccTrim                   uint16 = 0xf0
	MSPServoMixRules             uint16 = 0xf1
	MSPSetServoMixRule           uint16 = 0xf2
	MSPSetPassthrough            uint16 = 0xf5
	MSPSetRtc                    uint16 = 0xf6
	MSPRtc                       uint16 = 0xf7
	MSPSetBoardInfo              uint16 = 0xf8
	MSPSetSignature              uint16 = 0xf9
	MSPEepromWrite               uint16 = 0xfa
	MSPReserve1                  uint16 = 0xfb
	MSPReserve2                  uint16 = 0xfc
	MSPDebugmsg                  uint16 = 0xfd
	MSPDebug                     uint16 = 0xfe
	MSPV2Frame                   uint16 = 0xff
	MSP2CommonSerialConfig       uint16 = 0x1009
	MSP2CommonSetSerialConfig    uint16 = 0x100a
	MSP2SensorRangefinderLidarmt uint16 = 0x1f01
	MSP2SensorOpticalflowMt      uint16 = 0x1f02
	MSP2SensorGPS                uint16 = 0x1f03
	MSP2BetaflightBind           uint16 = 0x3000
	MSP2MotorOutputReordering    uint16 = 0x3001
	MSP2SetMotorOutputReordering uint16 = 0x3002
	MSP2SendDshotCommand         uint16 = 0x3003
	MSP2GetVTXDeviceStatus       uint16 = 0x3004
	MSP2GetOSDWarnings           uint16 = 0x3005
	MSP2GetText                  uint16 = 0x3006
	MSP2SetText                  uint16 = 0x3007
	MSP2GetLedStripConfigValues  uint16 = 0x3008
	MSP2SetLedStripConfigValues  uint16 = 0x3009
	MSP2SensorConfigActive       uint16 = 0x300a
	MSP2SensorOpticalflow        uint16 = 0x300b
	MSP2McuInfo                  uint16 = 0x300c
	MSP2GyroSensorActive         uint16 = 0x300d
	MSP2BatteryProfile           uint16 = 0x300e
	MSP2SetBatteryProfile        uint16 = 0x300f
	MSP2CLISetting               uint16 = 0x3010
	MSP2CLISettingInfo           uint16 = 0x3011
)

func init() {
	RegisterCommands([]CommandMeta{
		{Name: "MSP_API_VERSION", Code: MSPAPIVersion, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 94},
		{Name: "MSP_FC_VARIANT", Code: MSPFCVariant, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 95},
		{Name: "MSP_FC_VERSION", Code: MSPFCVersion, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 96},
		{Name: "MSP_BOARD_INFO", Code: MSPBoardInfo, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 97},
		{Name: "MSP_BUILD_INFO", Code: MSPBuildInfo, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 98},
		{Name: "MSP_NAME", Code: MSPName, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 100},
		{Name: "MSP_SET_NAME", Code: MSPSetName, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 101},
		{Name: "MSP_BATTERY_CONFIG", Code: MSPBatteryConfig, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 104},
		{Name: "MSP_SET_BATTERY_CONFIG", Code: MSPSetBatteryConfig, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 105},
		{Name: "MSP_MODE_RANGES", Code: MSPModeRanges, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 106},
		{Name: "MSP_SET_MODE_RANGE", Code: MSPSetModeRange, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 107},
		{Name: "MSP_FEATURE_CONFIG", Code: MSPFeatureConfig, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 108},
		{Name: "MSP_SET_FEATURE_CONFIG", Code: MSPSetFeatureConfig, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 109},
		{Name: "MSP_BOARD_ALIGNMENT_CONFIG", Code: MSPBoardAlignmentConfig, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 110},
		{Name: "MSP_SET_BOARD_ALIGNMENT_CONFIG", Code: MSPSetBoardAlignmentConfig, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 111},
		{Name: "MSP_CURRENT_METER_CONFIG", Code: MSPCurrentMeterConfig, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 112},
		{Name: "MSP_SET_CURRENT_METER_CONFIG", Code: MSPSetCurrentMeterConfig, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 113},
		{Name: "MSP_MIXER_CONFIG", Code: MSPMixerConfig, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 114},
		{Name: "MSP_SET_MIXER_CONFIG", Code: MSPSetMixerConfig, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 115},
		{Name: "MSP_RX_CONFIG", Code: MSPRXConfig, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 116},
		{Name: "MSP_SET_RX_CONFIG", Code: MSPSetRXConfig, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 117},
		{Name: "MSP_LED_COLORS", Code: MSPLedColors, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 118},
		{Name: "MSP_SET_LED_COLORS", Code: MSPSetLedColors, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 119},
		{Name: "MSP_LED_STRIP_CONFIG", Code: MSPLedStripConfig, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 120},
		{Name: "MSP_SET_LED_STRIP_CONFIG", Code: MSPSetLedStripConfig, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 121},
		{Name: "MSP_RSSI_CONFIG", Code: MSPRSSIConfig, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 122},
		{Name: "MSP_SET_RSSI_CONFIG", Code: MSPSetRSSIConfig, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 123},
		{Name: "MSP_ADJUSTMENT_RANGES", Code: MSPAdjustmentRanges, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 124},
		{Name: "MSP_SET_ADJUSTMENT_RANGE", Code: MSPSetAdjustmentRange, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 125},
		{Name: "MSP_CF_SERIAL_CONFIG", Code: MSPCFSerialConfig, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 126},
		{Name: "MSP_SET_CF_SERIAL_CONFIG", Code: MSPSetCFSerialConfig, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 127},
		{Name: "MSP_VOLTAGE_METER_CONFIG", Code: MSPVoltageMeterConfig, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 128},
		{Name: "MSP_SET_VOLTAGE_METER_CONFIG", Code: MSPSetVoltageMeterConfig, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 129},
		{Name: "MSP_SONAR_ALTITUDE", Code: MSPSonarAltitude, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 130},
		{Name: "MSP_PID_CONTROLLER", Code: MSPPIDController, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 131},
		{Name: "MSP_SET_PID_CONTROLLER", Code: MSPSetPIDController, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 132},
		{Name: "MSP_ARMING_CONFIG", Code: MSPArmingConfig, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 133},
		{Name: "MSP_SET_ARMING_CONFIG", Code: MSPSetArmingConfig, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 134},
		{Name: "MSP_RX_MAP", Code: MSPRXMap, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 137},
		{Name: "MSP_SET_RX_MAP", Code: MSPSetRXMap, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 138},
		{Name: "MSP_REBOOT", Code: MSPReboot, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 139},
		{Name: "MSP_DATAFLASH_SUMMARY", Code: MSPDataflashSummary, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 140},
		{Name: "MSP_DATAFLASH_READ", Code: MSPDataflashRead, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 141},
		{Name: "MSP_DATAFLASH_ERASE", Code: MSPDataflashErase, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 142},
		{Name: "MSP_FAILSAFE_CONFIG", Code: MSPFailsafeConfig, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 143},
		{Name: "MSP_SET_FAILSAFE_CONFIG", Code: MSPSetFailsafeConfig, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 144},
		{Name: "MSP_RXFAIL_CONFIG", Code: MSPRxfailConfig, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 145},
		{Name: "MSP_SET_RXFAIL_CONFIG", Code: MSPSetRxfailConfig, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 146},
		{Name: "MSP_SDCARD_SUMMARY", Code: MSPSdcardSummary, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 147},
		{Name: "MSP_BLACKBOX_CONFIG", Code: MSPBlackboxConfig, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 148},
		{Name: "MSP_SET_BLACKBOX_CONFIG", Code: MSPSetBlackboxConfig, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 149},
		{Name: "MSP_TRANSPONDER_CONFIG", Code: MSPTransponderConfig, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 150},
		{Name: "MSP_SET_TRANSPONDER_CONFIG", Code: MSPSetTransponderConfig, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 151},
		{Name: "MSP_OSD_CONFIG", Code: MSPOSDConfig, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 152},
		{Name: "MSP_SET_OSD_CONFIG", Code: MSPSetOSDConfig, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 153},
		{Name: "MSP_OSD_CHAR_READ", Code: MSPOSDCharRead, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 154},
		{Name: "MSP_OSD_CHAR_WRITE", Code: MSPOSDCharWrite, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 155},
		{Name: "MSP_VTX_CONFIG", Code: MSPVTXConfig, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 156},
		{Name: "MSP_SET_VTX_CONFIG", Code: MSPSetVTXConfig, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 157},
		{Name: "MSP_ADVANCED_CONFIG", Code: MSPAdvancedConfig, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 160},
		{Name: "MSP_SET_ADVANCED_CONFIG", Code: MSPSetAdvancedConfig, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 161},
		{Name: "MSP_FILTER_CONFIG", Code: MSPFilterConfig, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 162},
		{Name: "MSP_SET_FILTER_CONFIG", Code: MSPSetFilterConfig, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 163},
		{Name: "MSP_PID_ADVANCED", Code: MSPPIDAdvanced, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 164},
		{Name: "MSP_SET_PID_ADVANCED", Code: MSPSetPIDAdvanced, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 165},
		{Name: "MSP_SENSOR_CONFIG", Code: MSPSensorConfig, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 166},
		{Name: "MSP_SET_SENSOR_CONFIG", Code: MSPSetSensorConfig, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 167},
		{Name: "MSP_CAMERA_CONTROL", Code: MSPCameraControl, Protocol: 1, Direction: DirectionBoth, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 168},
		{Name: "MSP_SET_ARMING_DISABLED", Code: MSPSetArmingDisabled, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 169},
		{Name: "MSP_STATUS", Code: MSPStatus, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 172},
		{Name: "MSP_RAW_IMU", Code: MSPRawImu, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 173},
		{Name: "MSP_SERVO", Code: MSPServo, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 174},
		{Name: "MSP_MOTOR", Code: MSPMotor, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 175},
		{Name: "MSP_RC", Code: MSPRC, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 176},
		{Name: "MSP_RAW_GPS", Code: MSPRawGPS, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 177},
		{Name: "MSP_COMP_GPS", Code: MSPCompGPS, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 178},
		{Name: "MSP_ATTITUDE", Code: MSPAttitude, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 179},
		{Name: "MSP_ALTITUDE", Code: MSPAltitude, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 180},
		{Name: "MSP_ANALOG", Code: MSPAnalog, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 181},
		{Name: "MSP_RC_TUNING", Code: MSPRCTuning, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 182},
		{Name: "MSP_PID", Code: MSPPID, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 183},
		{Name: "MSP_BOXNAMES", Code: MSPBoxnames, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 184},
		{Name: "MSP_PIDNAMES", Code: MSPPidnames, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 185},
		{Name: "MSP_WP", Code: MSPWp, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 186},
		{Name: "MSP_BOXIDS", Code: MSPBoxids, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 187},
		{Name: "MSP_SERVO_CONFIGURATIONS", Code: MSPServoConfigurations, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 188},
		{Name: "MSP_NAV_STATUS", Code: MSPNavStatus, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 189},
		{Name: "MSP_NAV_CONFIG", Code: MSPNavConfig, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 190},
		{Name: "MSP_MOTOR_3D_CONFIG", Code: MSPMotor3dConfig, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 191},
		{Name: "MSP_RC_DEADBAND", Code: MSPRCDeadband, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 192},
		{Name: "MSP_SENSOR_ALIGNMENT", Code: MSPSensorAlignment, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 193},
		{Name: "MSP_LED_STRIP_MODECOLOR", Code: MSPLedStripModecolor, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 194},
		{Name: "MSP_VOLTAGE_METERS", Code: MSPVoltageMeters, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 195},
		{Name: "MSP_CURRENT_METERS", Code: MSPCurrentMeters, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 196},
		{Name: "MSP_BATTERY_STATE", Code: MSPBatteryState, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 197},
		{Name: "MSP_MOTOR_CONFIG", Code: MSPMotorConfig, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 198},
		{Name: "MSP_GPS_CONFIG", Code: MSPGPSConfig, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 199},
		{Name: "MSP_COMPASS_CONFIG", Code: MSPCompassConfig, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 200},
		{Name: "MSP_ESC_SENSOR_DATA", Code: MSPESCSensorData, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 201},
		{Name: "MSP_GPS_RESCUE", Code: MSPGPSRescue, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 202},
		{Name: "MSP_GPS_RESCUE_PIDS", Code: MSPGPSRescuePids, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 203},
		{Name: "MSP_VTXTABLE_BAND", Code: MSPVtxtableBand, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 204},
		{Name: "MSP_VTXTABLE_POWERLEVEL", Code: MSPVtxtablePowerlevel, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 205},
		{Name: "MSP_MOTOR_TELEMETRY", Code: MSPMotorTelemetry, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 206},
		{Name: "MSP_SIMPLIFIED_TUNING", Code: MSPSimplifiedTuning, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 209},
		{Name: "MSP_SET_SIMPLIFIED_TUNING", Code: MSPSetSimplifiedTuning, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 210},
		{Name: "MSP_CALCULATE_SIMPLIFIED_PID", Code: MSPCalculateSimplifiedPID, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 211},
		{Name: "MSP_CALCULATE_SIMPLIFIED_GYRO", Code: MSPCalculateSimplifiedGyro, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 212},
		{Name: "MSP_CALCULATE_SIMPLIFIED_DTERM", Code: MSPCalculateSimplifiedDterm, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 213},
		{Name: "MSP_VALIDATE_SIMPLIFIED_TUNING", Code: MSPValidateSimplifiedTuning, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 214},
		{Name: "MSP_STATUS_EX", Code: MSPStatusEx, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 217},
		{Name: "MSP_UID", Code: MSPUID, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 218},
		{Name: "MSP_GPSSVINFO", Code: MSPGpssvinfo, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 219},
		{Name: "MSP_GPSSTATISTICS", Code: MSPGpsstatistics, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 220},
		{Name: "MSP_ATTITUDE_QUATERNION", Code: MSPAttitudeQuaternion, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 221},
		{Name: "MSP_OSD_VIDEO_CONFIG", Code: MSPOSDVideoConfig, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 224},
		{Name: "MSP_SET_OSD_VIDEO_CONFIG", Code: MSPSetOSDVideoConfig, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 225},
		{Name: "MSP_DISPLAYPORT", Code: MSPDisplayport, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 226},
		{Name: "MSP_COPY_PROFILE", Code: MSPCopyProfile, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 227},
		{Name: "MSP_BEEPER_CONFIG", Code: MSPBeeperConfig, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 228},
		{Name: "MSP_SET_BEEPER_CONFIG", Code: MSPSetBeeperConfig, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 229},
		{Name: "MSP_SET_TX_INFO", Code: MSPSetTxInfo, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 230},
		{Name: "MSP_TX_INFO", Code: MSPTxInfo, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 231},
		{Name: "MSP_SET_OSD_CANVAS", Code: MSPSetOSDCanvas, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 232},
		{Name: "MSP_OSD_CANVAS", Code: MSPOSDCanvas, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 233},
		{Name: "MSP_SET_RAW_RC", Code: MSPSetRawRC, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 236},
		{Name: "MSP_SET_RAW_GPS", Code: MSPSetRawGPS, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 237},
		{Name: "MSP_SET_PID", Code: MSPSetPID, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 238},
		{Name: "MSP_SET_RC_TUNING", Code: MSPSetRCTuning, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 239},
		{Name: "MSP_ACC_CALIBRATION", Code: MSPAccCalibration, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 240},
		{Name: "MSP_MAG_CALIBRATION", Code: MSPMagCalibration, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 241},
		{Name: "MSP_RESET_CONF", Code: MSPResetConf, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 242},
		{Name: "MSP_SET_WP", Code: MSPSetWp, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 243},
		{Name: "MSP_SELECT_SETTING", Code: MSPSelectSetting, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 244},
		{Name: "MSP_SET_HEADING", Code: MSPSetHeading, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 245},
		{Name: "MSP_SET_SERVO_CONFIGURATION", Code: MSPSetServoConfiguration, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 246},
		{Name: "MSP_SET_MOTOR", Code: MSPSetMotor, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 247},
		{Name: "MSP_SET_NAV_CONFIG", Code: MSPSetNavConfig, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 248},
		{Name: "MSP_SET_MOTOR_3D_CONFIG", Code: MSPSetMotor3dConfig, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 249},
		{Name: "MSP_SET_RC_DEADBAND", Code: MSPSetRCDeadband, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 250},
		{Name: "MSP_SET_RESET_CURR_PID", Code: MSPSetResetCurrPID, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 251},
		{Name: "MSP_SET_SENSOR_ALIGNMENT", Code: MSPSetSensorAlignment, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 252},
		{Name: "MSP_SET_LED_STRIP_MODECOLOR", Code: MSPSetLedStripModecolor, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 253},
		{Name: "MSP_SET_MOTOR_CONFIG", Code: MSPSetMotorConfig, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 254},
		{Name: "MSP_SET_GPS_CONFIG", Code: MSPSetGPSConfig, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 255},
		{Name: "MSP_SET_COMPASS_CONFIG", Code: MSPSetCompassConfig, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 256},
		{Name: "MSP_SET_GPS_RESCUE", Code: MSPSetGPSRescue, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 257},
		{Name: "MSP_SET_GPS_RESCUE_PIDS", Code: MSPSetGPSRescuePids, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 258},
		{Name: "MSP_SET_VTXTABLE_BAND", Code: MSPSetVtxtableBand, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 259},
		{Name: "MSP_SET_VTXTABLE_POWERLEVEL", Code: MSPSetVtxtablePowerlevel, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 260},
		{Name: "MSP_MULTIPLE_MSP", Code: MSPMultipleMsp, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 263},
		{Name: "MSP_MODE_RANGES_EXTRA", Code: MSPModeRangesExtra, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 264},
		{Name: "MSP_SET_ACC_TRIM", Code: MSPSetAccTrim, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 265},
		{Name: "MSP_ACC_TRIM", Code: MSPAccTrim, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 266},
		{Name: "MSP_SERVO_MIX_RULES", Code: MSPServoMixRules, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 267},
		{Name: "MSP_SET_SERVO_MIX_RULE", Code: MSPSetServoMixRule, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 268},
		{Name: "MSP_SET_PASSTHROUGH", Code: MSPSetPassthrough, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 269},
		{Name: "MSP_SET_RTC", Code: MSPSetRtc, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 270},
		{Name: "MSP_RTC", Code: MSPRtc, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 271},
		{Name: "MSP_SET_BOARD_INFO", Code: MSPSetBoardInfo, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 272},
		{Name: "MSP_SET_SIGNATURE", Code: MSPSetSignature, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 273},
		{Name: "MSP_EEPROM_WRITE", Code: MSPEepromWrite, Protocol: 1, Direction: DirectionWrite, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 274},
		{Name: "MSP_RESERVE_1", Code: MSPReserve1, Protocol: 1, Direction: DirectionUnknown, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 275},
		{Name: "MSP_RESERVE_2", Code: MSPReserve2, Protocol: 1, Direction: DirectionUnknown, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 276},
		{Name: "MSP_DEBUGMSG", Code: MSPDebugmsg, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 277},
		{Name: "MSP_DEBUG", Code: MSPDebug, Protocol: 1, Direction: DirectionRead, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 278},
		{Name: "MSP_V2_FRAME", Code: MSPV2Frame, Protocol: 1, Direction: DirectionUnknown, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol.h", Line: 279},
		{Name: "MSP2_COMMON_SERIAL_CONFIG", Code: MSP2CommonSerialConfig, Protocol: 2, Direction: DirectionUnknown, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol_v2_common.h", Line: 21},
		{Name: "MSP2_COMMON_SET_SERIAL_CONFIG", Code: MSP2CommonSetSerialConfig, Protocol: 2, Direction: DirectionUnknown, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol_v2_common.h", Line: 22},
		{Name: "MSP2_SENSOR_RANGEFINDER_LIDARMT", Code: MSP2SensorRangefinderLidarmt, Protocol: 2, Direction: DirectionUnknown, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol_v2_common.h", Line: 27},
		{Name: "MSP2_SENSOR_OPTICALFLOW_MT", Code: MSP2SensorOpticalflowMt, Protocol: 2, Direction: DirectionUnknown, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol_v2_common.h", Line: 28},
		{Name: "MSP2_SENSOR_GPS", Code: MSP2SensorGPS, Protocol: 2, Direction: DirectionUnknown, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol_v2_common.h", Line: 25},
		{Name: "MSP2_BETAFLIGHT_BIND", Code: MSP2BetaflightBind, Protocol: 2, Direction: DirectionUnknown, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol_v2_betaflight.h", Line: 21},
		{Name: "MSP2_MOTOR_OUTPUT_REORDERING", Code: MSP2MotorOutputReordering, Protocol: 2, Direction: DirectionUnknown, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol_v2_betaflight.h", Line: 22},
		{Name: "MSP2_SET_MOTOR_OUTPUT_REORDERING", Code: MSP2SetMotorOutputReordering, Protocol: 2, Direction: DirectionUnknown, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol_v2_betaflight.h", Line: 23},
		{Name: "MSP2_SEND_DSHOT_COMMAND", Code: MSP2SendDshotCommand, Protocol: 2, Direction: DirectionUnknown, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol_v2_betaflight.h", Line: 24},
		{Name: "MSP2_GET_VTX_DEVICE_STATUS", Code: MSP2GetVTXDeviceStatus, Protocol: 2, Direction: DirectionUnknown, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol_v2_betaflight.h", Line: 25},
		{Name: "MSP2_GET_OSD_WARNINGS", Code: MSP2GetOSDWarnings, Protocol: 2, Direction: DirectionUnknown, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol_v2_betaflight.h", Line: 26},
		{Name: "MSP2_GET_TEXT", Code: MSP2GetText, Protocol: 2, Direction: DirectionUnknown, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol_v2_betaflight.h", Line: 27},
		{Name: "MSP2_SET_TEXT", Code: MSP2SetText, Protocol: 2, Direction: DirectionUnknown, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol_v2_betaflight.h", Line: 28},
		{Name: "MSP2_GET_LED_STRIP_CONFIG_VALUES", Code: MSP2GetLedStripConfigValues, Protocol: 2, Direction: DirectionUnknown, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol_v2_betaflight.h", Line: 29},
		{Name: "MSP2_SET_LED_STRIP_CONFIG_VALUES", Code: MSP2SetLedStripConfigValues, Protocol: 2, Direction: DirectionUnknown, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol_v2_betaflight.h", Line: 30},
		{Name: "MSP2_SENSOR_CONFIG_ACTIVE", Code: MSP2SensorConfigActive, Protocol: 2, Direction: DirectionUnknown, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol_v2_betaflight.h", Line: 31},
		{Name: "MSP2_SENSOR_OPTICALFLOW", Code: MSP2SensorOpticalflow, Protocol: 2, Direction: DirectionUnknown, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol_v2_betaflight.h", Line: 32},
		{Name: "MSP2_MCU_INFO", Code: MSP2McuInfo, Protocol: 2, Direction: DirectionUnknown, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol_v2_betaflight.h", Line: 33},
		{Name: "MSP2_GYRO_SENSOR_ACTIVE", Code: MSP2GyroSensorActive, Protocol: 2, Direction: DirectionUnknown, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol_v2_betaflight.h", Line: 34},
		{Name: "MSP2_BATTERY_PROFILE", Code: MSP2BatteryProfile, Protocol: 2, Direction: DirectionUnknown, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol_v2_betaflight.h", Line: 35},
		{Name: "MSP2_SET_BATTERY_PROFILE", Code: MSP2SetBatteryProfile, Protocol: 2, Direction: DirectionUnknown, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol_v2_betaflight.h", Line: 36},
		{Name: "MSP2_CLI_SETTING", Code: MSP2CLISetting, Protocol: 2, Direction: DirectionUnknown, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol_v2_betaflight.h", Line: 37},
		{Name: "MSP2_CLI_SETTING_INFO", Code: MSP2CLISettingInfo, Protocol: 2, Direction: DirectionUnknown, SourceVersion: "2026.6.1", Source: "src/main/msp/msp_protocol_v2_betaflight.h", Line: 38},
	})
}
