package generate

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
)

func WriteMSPRegistry(commands []MSPCommand, sourceVersion string) ([]byte, error) {
	var b bytes.Buffer
	writeGeneratedHeader(&b, sourceVersion)
	b.WriteString("package msp\n\n")
	fmt.Fprintf(&b, "const GeneratedMSPSourceVersion = %q\n\n", sourceVersion)
	b.WriteString("const (\n")
	for _, command := range commands {
		fmt.Fprintf(&b, "\t%s uint16 = %#x\n", goConstName(command.Name), command.Code)
	}
	b.WriteString(")\n\n")
	b.WriteString("func init() {\n")
	b.WriteString("\tRegisterCommands([]CommandMeta{\n")
	for _, command := range commands {
		fmt.Fprintf(&b, "\t\t{Name: %q, Code: %s, Protocol: %d, Direction: Direction%s, SourceVersion: %q, Source: %q, Line: %d},\n",
			command.Name,
			goConstName(command.Name),
			command.Protocol,
			directionConst(command.Direction),
			sourceVersion,
			command.Source,
			command.Line,
		)
	}
	b.WriteString("\t})\n")
	b.WriteString("}\n")
	return format.Source(b.Bytes())
}

func WriteSettingsRegistry(settings []SettingMetadata, sourceVersion string, sourceFiles []string) ([]byte, error) {
	var b bytes.Buffer
	writeGeneratedHeader(&b, sourceVersion)
	b.WriteString("package settings\n\n")
	b.WriteString("func init() {\n")
	b.WriteString("\tDefaultRegistry = generatedRegistry()\n")
	b.WriteString("}\n\n")
	b.WriteString("func generatedRegistry() Registry {\n")
	b.WriteString("\tsettings := []Metadata{\n")
	for _, setting := range settings {
		fmt.Fprintf(&b, "\t\t{Name: %q, Type: %s, Scope: %q, Mode: %q",
			setting.Name,
			settingsTypeConst(setting.Type),
			setting.Scope,
			setting.Mode,
		)
		writeIntPtrField(&b, "Min", setting.Min)
		writeIntPtrField(&b, "Max", setting.Max)
		writeStringField(&b, "MinExpression", setting.MinExpression)
		writeStringField(&b, "MaxExpression", setting.MaxExpression)
		writeStringField(&b, "LookupTable", setting.LookupTable)
		if len(setting.Lookup) > 0 {
			fmt.Fprintf(&b, ", Lookup: []string{%s}", quotedStrings(setting.Lookup))
		}
		writeIntPtrField(&b, "BitPosition", setting.BitPosition)
		writeIntPtrField(&b, "MinLength", setting.MinLength)
		writeIntPtrField(&b, "MaxLength", setting.MaxLength)
		writeStringField(&b, "PG", setting.PG)
		if setting.Line != 0 {
			fmt.Fprintf(&b, ", Line: %d", setting.Line)
		}
		fmt.Fprintf(&b, ", Source: %q},\n", setting.Source)
	}
	b.WriteString("\t}\n")
	b.WriteString("\treturn newRegistryWithSource(")
	fmt.Fprintf(&b, "%q, []string{%s}, true, settings", sourceVersion, quotedStrings(sourceFiles))
	b.WriteString(")\n")
	b.WriteString("}\n")
	return format.Source(b.Bytes())
}

func writeGeneratedHeader(b *bytes.Buffer, sourceVersion string) {
	b.WriteString("// Code generated by betaflight-cli internal/generate. DO NOT EDIT.\n")
	fmt.Fprintf(b, "// Source metadata derived from Betaflight %s under GPL-3.0-or-later.\n", sourceVersion)
	b.WriteString("// See LICENSE and THIRD_PARTY_NOTICES.md.\n")
}

func goConstName(name string) string {
	parts := strings.Split(strings.ToLower(strings.TrimPrefix(name, "MSP_")), "_")
	if strings.HasPrefix(name, "MSP2_") {
		parts = strings.Split(strings.ToLower(strings.TrimPrefix(name, "MSP2_")), "_")
		return "MSP2" + titleParts(parts)
	}
	return "MSP" + titleParts(parts)
}

func titleParts(parts []string) string {
	var out strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		switch part {
		case "api":
			out.WriteString("API")
		case "cli":
			out.WriteString("CLI")
		case "fc":
			out.WriteString("FC")
		case "cf":
			out.WriteString("CF")
		case "osd":
			out.WriteString("OSD")
		case "vtx":
			out.WriteString("VTX")
		case "gps":
			out.WriteString("GPS")
		case "rc":
			out.WriteString("RC")
		case "rx":
			out.WriteString("RX")
		case "pid":
			out.WriteString("PID")
		case "dterm":
			out.WriteString("Dterm")
		case "rssi":
			out.WriteString("RSSI")
		case "esc":
			out.WriteString("ESC")
		case "uid":
			out.WriteString("UID")
		default:
			out.WriteString(strings.ToUpper(part[:1]))
			out.WriteString(part[1:])
		}
	}
	return out.String()
}

func directionConst(direction string) string {
	switch direction {
	case "read":
		return "Read"
	case "write":
		return "Write"
	case "both":
		return "Both"
	default:
		return "Unknown"
	}
}

func settingsTypeConst(typ string) string {
	switch typ {
	case "int":
		return "TypeInt"
	case "uint":
		return "TypeUint"
	case "lookup":
		return "TypeLookup"
	case "string":
		return "TypeString"
	default:
		return "ValueType(\"unknown\")"
	}
}

func writeIntPtrField(b *bytes.Buffer, name string, value *int64) {
	if value != nil {
		fmt.Fprintf(b, ", %s: int64Ptr(%d)", name, *value)
	}
}

func writeStringField(b *bytes.Buffer, name, value string) {
	if value != "" {
		fmt.Fprintf(b, ", %s: %q", name, value)
	}
}

func quotedStrings(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, fmt.Sprintf("%q", value))
	}
	return strings.Join(quoted, ", ")
}
